# Generated by Django 4.2.30 on 2026-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_dailypet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='coat_color',
            field=models.CharField(choices=[('deep_blue', 'Deep Blue'), ('periwinkle', 'Periwinkle'), ('dusty_violet', 'Dusty Violet'), ('mint', 'Mint'), ('rose', 'Rose'), ('honey', 'Honey'), ('ink_brown', 'Ink Brown'), ('classic', 'Classic Black')], default='deep_blue', max_length=20),
        ),
    ]
